### ISSUE TITLE
Projucer .jucer file

### ISSUE THREAD

**Issue by crshrprt** [nicolagulmini/plugins#2]
I would like to build this plugin on Linux. However I don't know how to do it without the .jucer file.

Is there any chance the jucer file will be included in this repo?

**Comment by nicolagulmini** [comment]
I thought of this repo to keep only the processor and editor code, so I can keep track of my progress as a JUCE beginner... but if you want to install and use the plugin, I would ask you to wait for the final version, as it returns some validation issues with my DAW and I also want to change the distortion. Thank you again for your interest!

**Comment by crshrprt** [comment]
No problem, if and when you'll need a feedback on Linux I'll gladly help.
